# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/clctj/snail2024_GPT/type_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Text_win(object):
    def setupUi(self, Text_win):
        Text_win.setObjectName("Text_win")
        Text_win.resize(1180, 841)
        Text_win.setMinimumSize(QtCore.QSize(0, 0))
        Text_win.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Text_win.setStyleSheet("background-image: url(:/snail/qrc/玻璃背景2.png);")
        self.tools1 = QtWidgets.QGroupBox(Text_win)
        self.tools1.setGeometry(QtCore.QRect(260, 720, 621, 33))
        self.tools1.setFlat(True)
        self.tools1.setObjectName("tools1")
        self.boy = QtWidgets.QCheckBox(self.tools1)
        self.boy.setGeometry(QtCore.QRect(180, 0, 61, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/snail/qrc/boy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boy.setIcon(icon)
        self.boy.setIconSize(QtCore.QSize(32, 32))
        self.boy.setChecked(True)
        self.boy.setAutoExclusive(True)
        self.boy.setObjectName("boy")
        self.gril = QtWidgets.QCheckBox(self.tools1)
        self.gril.setGeometry(QtCore.QRect(250, 0, 61, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/snail/qrc/gril.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gril.setIcon(icon1)
        self.gril.setIconSize(QtCore.QSize(32, 32))
        self.gril.setAutoRepeat(False)
        self.gril.setAutoExclusive(True)
        self.gril.setObjectName("gril")
        self.big = QtWidgets.QPushButton(self.tools1)
        self.big.setGeometry(QtCore.QRect(90, 0, 35, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/snail/qrc/zoom-in-symbolic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.big.setIcon(icon2)
        self.big.setIconSize(QtCore.QSize(32, 32))
        self.big.setFlat(False)
        self.big.setObjectName("big")
        self.small = QtWidgets.QPushButton(self.tools1)
        self.small.setGeometry(QtCore.QRect(140, 0, 35, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/snail/qrc/zoom-out-symbolic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.small.setIcon(icon3)
        self.small.setIconSize(QtCore.QSize(32, 32))
        self.small.setFlat(False)
        self.small.setObjectName("small")
        self.woman = QtWidgets.QCheckBox(self.tools1)
        self.woman.setGeometry(QtCore.QRect(400, 0, 61, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/snail/qrc/woman.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.woman.setIcon(icon4)
        self.woman.setIconSize(QtCore.QSize(32, 32))
        self.woman.setAutoRepeat(False)
        self.woman.setAutoExclusive(True)
        self.woman.setObjectName("woman")
        self.man = QtWidgets.QCheckBox(self.tools1)
        self.man.setGeometry(QtCore.QRect(320, 0, 61, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/snail/qrc/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.man.setIcon(icon5)
        self.man.setIconSize(QtCore.QSize(32, 32))
        self.man.setCheckable(True)
        self.man.setChecked(False)
        self.man.setAutoRepeat(False)
        self.man.setAutoExclusive(True)
        self.man.setObjectName("man")
        self.set_gpt = QtWidgets.QPushButton(self.tools1)
        self.set_gpt.setGeometry(QtCore.QRect(0, 0, 32, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/snail/qrc/32系统设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_gpt.setIcon(icon6)
        self.set_gpt.setIconSize(QtCore.QSize(32, 32))
        self.set_gpt.setCheckable(False)
        self.set_gpt.setObjectName("set_gpt")
        self.repet = QtWidgets.QPushButton(self.tools1)
        self.repet.setGeometry(QtCore.QRect(50, 0, 32, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/snail/qrc/32重复.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/snail/qrc/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.repet.setIcon(icon7)
        self.repet.setIconSize(QtCore.QSize(32, 32))
        self.repet.setCheckable(True)
        self.repet.setObjectName("repet")
        self.role_list = QtWidgets.QComboBox(self.tools1)
        self.role_list.setGeometry(QtCore.QRect(460, 0, 151, 32))
        self.role_list.setObjectName("role_list")
        self.role_list.addItem("")
        self.role_list.addItem("")
        self.role_list.addItem("")
        self.role_list.addItem("")
        self.role_list.addItem("")
        self.role_list.addItem("")
        self.type_text = QtWidgets.QTextBrowser(Text_win)
        self.type_text.setGeometry(QtCore.QRect(260, 10, 911, 681))
        self.type_text.setStyleSheet("background-image: url(:/snail/qrc/米黄背景.png);")
        self.type_text.setReadOnly(False)
        self.type_text.setOpenExternalLinks(True)
        self.type_text.setObjectName("type_text")
        self.listView = QtWidgets.QListView(Text_win)
        self.listView.setGeometry(QtCore.QRect(10, 10, 241, 681))
        self.listView.setStyleSheet("background-image: url(:/snail/qrc/米黄背景.png);")
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView.setProperty("isWrapping", False)
        self.listView.setWordWrap(False)
        self.listView.setObjectName("listView")
        self.question_Text = QtWidgets.QTextEdit(Text_win)
        self.question_Text.setGeometry(QtCore.QRect(260, 760, 871, 71))
        self.question_Text.setStyleSheet("color: rgb(0, 85, 255);")
        self.question_Text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.question_Text.setMarkdown("")
        self.question_Text.setObjectName("question_Text")
        self.Snail_Gpt = QtWidgets.QPushButton(Text_win)
        self.Snail_Gpt.setGeometry(QtCore.QRect(30, 770, 64, 64))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/snail/qrc/64snailgpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/snail/qrc/48信息框.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Snail_Gpt.setIcon(icon8)
        self.Snail_Gpt.setIconSize(QtCore.QSize(64, 64))
        self.Snail_Gpt.setCheckable(True)
        self.Snail_Gpt.setFlat(True)
        self.Snail_Gpt.setObjectName("Snail_Gpt")
        self.Submit = QtWidgets.QPushButton(Text_win)
        self.Submit.setGeometry(QtCore.QRect(140, 770, 64, 64))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/snail/qrc/64gpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/snail/qrc/64gpt2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Submit.setIcon(icon9)
        self.Submit.setIconSize(QtCore.QSize(64, 64))
        self.Submit.setCheckable(True)
        self.Submit.setObjectName("Submit")
        self.tools2 = QtWidgets.QGroupBox(Text_win)
        self.tools2.setGeometry(QtCore.QRect(910, 710, 251, 51))
        self.tools2.setObjectName("tools2")
        self.quit = QtWidgets.QPushButton(self.tools2)
        self.quit.setGeometry(QtCore.QRect(200, 0, 48, 48))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/snail/qrc/48退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit.setIcon(icon10)
        self.quit.setIconSize(QtCore.QSize(48, 48))
        self.quit.setFlat(True)
        self.quit.setObjectName("quit")
        self.save_text = QtWidgets.QPushButton(self.tools2)
        self.save_text.setGeometry(QtCore.QRect(150, 0, 48, 48))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/snail/qrc/48保存1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_text.setIcon(icon11)
        self.save_text.setIconSize(QtCore.QSize(48, 48))
        self.save_text.setCheckable(False)
        self.save_text.setFlat(True)
        self.save_text.setObjectName("save_text")
        self.clear_text = QtWidgets.QPushButton(self.tools2)
        self.clear_text.setGeometry(QtCore.QRect(100, 0, 48, 48))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/snail/qrc/48清屏1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_text.setIcon(icon12)
        self.clear_text.setIconSize(QtCore.QSize(48, 48))
        self.clear_text.setCheckable(False)
        self.clear_text.setFlat(True)
        self.clear_text.setObjectName("clear_text")
        self.pinyin_b = QtWidgets.QPushButton(self.tools2)
        self.pinyin_b.setGeometry(QtCore.QRect(50, 0, 48, 48))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/snail/qrc/48拼音1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(":/snail/qrc/48拼音2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pinyin_b.setIcon(icon13)
        self.pinyin_b.setIconSize(QtCore.QSize(48, 48))
        self.pinyin_b.setCheckable(True)
        self.pinyin_b.setFlat(True)
        self.pinyin_b.setObjectName("pinyin_b")
        self.audio = QtWidgets.QPushButton(self.tools2)
        self.audio.setGeometry(QtCore.QRect(0, 0, 48, 48))
        self.audio.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/snail/qrc/48文本语音1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon14.addPixmap(QtGui.QPixmap(":/snail/qrc/48文本语音2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.audio.setIcon(icon14)
        self.audio.setIconSize(QtCore.QSize(48, 48))
        self.audio.setCheckable(True)
        self.audio.setChecked(False)
        self.audio.setFlat(False)
        self.audio.setObjectName("audio")
        self.play = QtWidgets.QPushButton(self.tools2)
        self.play.setGeometry(QtCore.QRect(0, 0, 48, 48))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/snail/qrc/48播放.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":/snail/qrc/48暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play.setIcon(icon15)
        self.play.setIconSize(QtCore.QSize(48, 48))
        self.play.setCheckable(True)
        self.play.setFlat(False)
        self.play.setObjectName("play")
        self.play.raise_()
        self.quit.raise_()
        self.save_text.raise_()
        self.clear_text.raise_()
        self.pinyin_b.raise_()
        self.audio.raise_()
        self.label = QtWidgets.QLabel(Text_win)
        self.label.setGeometry(QtCore.QRect(10, 700, 1161, 141))
        self.label.setStyleSheet("background-image: url(:/snail/qrc/hb3.jpg);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.clear_quest = QtWidgets.QPushButton(Text_win)
        self.clear_quest.setGeometry(QtCore.QRect(1130, 800, 32, 32))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/snail/qrc/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_quest.setIcon(icon16)
        self.clear_quest.setIconSize(QtCore.QSize(24, 24))
        self.clear_quest.setFlat(True)
        self.clear_quest.setObjectName("clear_quest")
        self.qianwen_b = QtWidgets.QCheckBox(Text_win)
        self.qianwen_b.setGeometry(QtCore.QRect(100, 720, 71, 31))
        self.qianwen_b.setObjectName("qianwen_b")
        self.buttonGroup = QtWidgets.QButtonGroup(Text_win)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.qianwen_b)
        self.xinhuo_b = QtWidgets.QCheckBox(Text_win)
        self.xinhuo_b.setGeometry(QtCore.QRect(20, 720, 71, 31))
        self.xinhuo_b.setChecked(True)
        self.xinhuo_b.setObjectName("xinhuo_b")
        self.buttonGroup.addButton(self.xinhuo_b)
        self.wenxin_b = QtWidgets.QCheckBox(Text_win)
        self.wenxin_b.setGeometry(QtCore.QRect(180, 720, 71, 31))
        self.wenxin_b.setObjectName("wenxin_b")
        self.buttonGroup.addButton(self.wenxin_b)
        self.label.raise_()
        self.tools1.raise_()
        self.type_text.raise_()
        self.listView.raise_()
        self.Snail_Gpt.raise_()
        self.Submit.raise_()
        self.tools2.raise_()
        self.question_Text.raise_()
        self.clear_quest.raise_()
        self.qianwen_b.raise_()
        self.xinhuo_b.raise_()
        self.wenxin_b.raise_()

        self.retranslateUi(Text_win)
        QtCore.QMetaObject.connectSlotsByName(Text_win)

    def retranslateUi(self, Text_win):
        _translate = QtCore.QCoreApplication.translate
        Text_win.setWindowTitle(_translate("Text_win", "Form"))
        self.role_list.setItemText(0, _translate("Text_win", "我的老师"))
        self.role_list.setItemText(1, _translate("Text_win", "写作助理"))
        self.role_list.setItemText(2, _translate("Text_win", "智能出题"))
        self.role_list.setItemText(3, _translate("Text_win", "中英翻译"))
        self.role_list.setItemText(4, _translate("Text_win", "文章润色"))
        self.role_list.setItemText(5, _translate("Text_win", "白话转文言"))
        self.type_text.setPlaceholderText(_translate("Text_win", "输入结束以后，选择转化语音或标注拼音。"))
        self.qianwen_b.setText(_translate("Text_win", "阿里"))
        self.xinhuo_b.setText(_translate("Text_win", "讯飞"))
        self.wenxin_b.setText(_translate("Text_win", "百度"))

import qxjyclass_rc
