# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/clctj/snail2024_GPT/snail_setGpt.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 485)
        Dialog.setMinimumSize(QtCore.QSize(630, 485))
        Dialog.setMaximumSize(QtCore.QSize(630, 16777215))
        Dialog.setSizeGripEnabled(True)
        self.xinhuo = QtWidgets.QGroupBox(Dialog)
        self.xinhuo.setGeometry(QtCore.QRect(40, 40, 291, 321))
        self.xinhuo.setObjectName("xinhuo")
        self.appid_edit = QtWidgets.QLineEdit(self.xinhuo)
        self.appid_edit.setGeometry(QtCore.QRect(100, 40, 181, 41))
        self.appid_edit.setObjectName("appid_edit")
        self.label = QtWidgets.QLabel(self.xinhuo)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 27))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.xinhuo)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.xinhuo)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 91, 27))
        self.label_3.setObjectName("label_3")
        self.api_secret_edit = QtWidgets.QLineEdit(self.xinhuo)
        self.api_secret_edit.setGeometry(QtCore.QRect(100, 90, 181, 41))
        self.api_secret_edit.setObjectName("api_secret_edit")
        self.api_key_edit = QtWidgets.QLineEdit(self.xinhuo)
        self.api_key_edit.setGeometry(QtCore.QRect(100, 140, 181, 41))
        self.api_key_edit.setObjectName("api_key_edit")
        self.label_4 = QtWidgets.QLabel(self.xinhuo)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 91, 27))
        self.label_4.setObjectName("label_4")
        self.domain_combobox = QtWidgets.QComboBox(self.xinhuo)
        self.domain_combobox.setGeometry(QtCore.QRect(10, 220, 261, 36))
        self.domain_combobox.setObjectName("domain_combobox")
        self.domain_combobox.addItem("")
        self.domain_combobox.addItem("")
        self.domain_combobox.addItem("")
        self.domain_combobox.addItem("")
        self.spark_url_label = QtWidgets.QLabel(self.xinhuo)
        self.spark_url_label.setGeometry(QtCore.QRect(10, 260, 261, 51))
        self.spark_url_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.spark_url_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.spark_url_label.setWordWrap(True)
        self.spark_url_label.setObjectName("spark_url_label")
        self.wenxin = QtWidgets.QGroupBox(Dialog)
        self.wenxin.setGeometry(QtCore.QRect(340, 50, 271, 191))
        self.wenxin.setObjectName("wenxin")
        self.label_5 = QtWidgets.QLabel(self.wenxin)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 81, 27))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.wenxin)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 101, 27))
        self.label_6.setObjectName("label_6")
        self.wx_appid_edit = QtWidgets.QLineEdit(self.wenxin)
        self.wx_appid_edit.setGeometry(QtCore.QRect(100, 40, 151, 41))
        self.wx_appid_edit.setObjectName("wx_appid_edit")
        self.wx_api_secret_edit = QtWidgets.QLineEdit(self.wenxin)
        self.wx_api_secret_edit.setGeometry(QtCore.QRect(10, 130, 241, 41))
        self.wx_api_secret_edit.setObjectName("wx_api_secret_edit")
        self.qianwen = QtWidgets.QGroupBox(Dialog)
        self.qianwen.setGeometry(QtCore.QRect(340, 250, 271, 111))
        self.qianwen.setObjectName("qianwen")
        self.label_7 = QtWidgets.QLabel(self.qianwen)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 81, 27))
        self.label_7.setObjectName("label_7")
        self.qw_appid_edit = QtWidgets.QLineEdit(self.qianwen)
        self.qw_appid_edit.setGeometry(QtCore.QRect(10, 60, 241, 41))
        self.qw_appid_edit.setObjectName("qw_appid_edit")
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setGeometry(QtCore.QRect(480, 420, 128, 39))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/snail/qrc/link_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon)
        self.save.setObjectName("save")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 370, 571, 41))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(150, 0, 301, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 410, 64, 64))
        self.label_10.setPixmap(QtGui.QPixmap(":/snail/qrc/64snailgpt.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.xinhuo.setTitle(_translate("Dialog", "科大讯飞_星火模型"))
        self.label.setText(_translate("Dialog", "APPID"))
        self.label_2.setText(_translate("Dialog", "APISecret"))
        self.label_3.setText(_translate("Dialog", "APIKey"))
        self.label_4.setText(_translate("Dialog", "星火Model"))
        self.domain_combobox.setItemText(0, _translate("Dialog", "general"))
        self.domain_combobox.setItemText(1, _translate("Dialog", "generalv2"))
        self.domain_combobox.setItemText(2, _translate("Dialog", "generalv3"))
        self.domain_combobox.setItemText(3, _translate("Dialog", "generalv3.5"))
        self.wenxin.setTitle(_translate("Dialog", "百度_文心一言"))
        self.label_5.setText(_translate("Dialog", "API Key"))
        self.label_6.setText(_translate("Dialog", "Secret Key"))
        self.qianwen.setTitle(_translate("Dialog", "阿里_通义千问"))
        self.label_7.setText(_translate("Dialog", "API-KEY"))
        self.save.setText(_translate("Dialog", "保存|退出"))
        self.label_8.setText(_translate("Dialog", "所有参数在对应的网站注册以后可获取，获取方法，网站有详细介绍。"))
        self.label_9.setText(_translate("Dialog", "   根据使用中的 GPT大模型 设置 参数"))

import qxjyclass_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

